version: '3'
services:
  jsp-helloworld:
    build: ./view-templates/jsp-helloworld
    volumes:
    - .:/springboot-tutorials
    - ~/.m2:/root/.m2
    working_dir: /springboot-tutorials
    ports:
    - 8080:8080
    command: bash -c "mvn -N clean install && cd view-templates/jsp-helloworld && mvn clean spring-boot:run"
